require:
  - rubocop-rails
  - rubocop-capybara
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - "config/initializers/**/*"
    - "config/environments/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/**/*"
